//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是由工具生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;

namespace DbOrm.Model
{
    /// <summary>
    /// 类型表、分类表
    /// </summary>
    public partial class Sys_Type : IModel
    {
        /// <summary>
        /// 
        /// </summary>
        public int? ID { set; get; }
        /// <summary>
        /// 
        /// </summary>
        public int? TypeID { set; get; }
        /// <summary>
        /// 
        /// </summary>
        public string Name { set; get; }
        /// <summary>
        /// 
        /// </summary>
        public string Temp1 { set; get; }
        /// <summary>
        /// 
        /// </summary>
        public string Temp2 { set; get; }
        /// <summary>
        /// 
        /// </summary>
        public string Temp3 { set; get; }
        /// <summary>
        /// 新增
        /// </summary>
        internal override string InsertSql()
        {
            return "insert into Sys_Type(TypeID,Name,Temp1,Temp2,Temp3) values(@TypeID,@Name,@Temp1,@Temp2,@Temp3)";
        }

        /// <summary>
        /// 修改
        /// </summary>
        internal override string UpdateSql()
        {
            StringBuilder str = new StringBuilder();
            if (TypeID != null) { str.AppendLine(",TypeID=@TypeID"); }
            if (Name != null) { str.AppendLine(",Name=@Name"); }
            if (Temp1 != null) { str.AppendLine(",Temp1=@Temp1"); }
            if (Temp2 != null) { str.AppendLine(",Temp2=@Temp2"); }
            if (Temp3 != null) { str.AppendLine(",Temp3=@Temp3"); }

            return "update Sys_Type set " + str.Remove(0, 1);
        }
    }
}

