//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是由工具生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;

namespace DbOrm.Model
{
    /// <summary>
    /// 管理员（后台登录）
    /// </summary>
    public partial class Sys_Admin : IModel
    {
        /// <summary>
        /// 
        /// </summary>
        public int? ID { set; get; }
        /// <summary>
        /// 用户名
        /// </summary>
        public string UserName { set; get; }
        /// <summary>
        /// 密码（加密后的字符串）
        /// </summary>
        public string UserPwd { set; get; }
        /// <summary>
        /// 新增
        /// </summary>
        internal override string InsertSql()
        {
            return "insert into Sys_Admin(UserName,UserPwd) values(@UserName,@UserPwd)";
        }

        /// <summary>
        /// 修改
        /// </summary>
        internal override string UpdateSql()
        {
            StringBuilder str = new StringBuilder();
            if (UserName != null) { str.AppendLine(",UserName=@UserName"); }
            if (UserPwd != null) { str.AppendLine(",UserPwd=@UserPwd"); }

            return "update Sys_Admin set " + str.Remove(0, 1);
        }
    }
}

