//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是由工具生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;

namespace DbOrm.Model
{
    /// <summary>
    /// Test_Main的明细表
    /// </summary>
    public partial class Test_MainDtl : IDAL
    {
        /// <summary>
        /// 主键
        /// </summary>
        public int? ID { set; get; }
        /// <summary>
        /// Test_Main表外键
        /// </summary>
        public int? Test_Main_ID { set; get; }
        /// <summary>
        /// 名称
        /// </summary>
        public string MainDtlName { set; get; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remark { set; get; }
        /// <summary>
        /// 新增
        /// </summary>
        internal override string Insert()
        {
            return "insert into Test_MainDtl(Test_Main_ID,MainDtlName,Remark) values(@Test_Main_ID,@MainDtlName,@Remark)";
        }

        /// <summary>
        /// 修改
        /// </summary>
        internal override string Update()
        {
            StringBuilder str = new StringBuilder();
            if (Test_Main_ID != null) { str.AppendLine(",Test_Main_ID=@Test_Main_ID"); }
            if (MainDtlName != null) { str.AppendLine(",MainDtlName=@MainDtlName"); }
            if (Remark != null) { str.AppendLine(",Remark=@Remark"); }

            return "update Test_MainDtl set " + str.Remove(0, 1);
        }
    }
}

