//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是由工具生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;

namespace DbOrm.Model
{
    /// <summary>
    /// Test模块类型表，与基础数据不同的是他只给Test模块用，也是为了后期的模块移植
    /// </summary>
    public partial class Test_Type : IModel
    {
        /// <summary>
        /// 主键
        /// </summary>
        public int? ID { set; get; }
        /// <summary>
        /// 编号
        /// </summary>
        public string TypeID { set; get; }
        /// <summary>
        /// 名称
        /// </summary>
        public string TypeName { set; get; }
        /// <summary>
        /// 新增
        /// </summary>
        internal override string InsertSql()
        {
            return "insert into Test_Type(TypeID,TypeName) values(@TypeID,@TypeName)";
        }

        /// <summary>
        /// 修改
        /// </summary>
        internal override string UpdateSql()
        {
            StringBuilder str = new StringBuilder();
            if (TypeID != null) { str.AppendLine(",TypeID=@TypeID"); }
            if (TypeName != null) { str.AppendLine(",TypeName=@TypeName"); }

            return "update Test_Type set " + str.Remove(0, 1);
        }
    }
}

